#!/usr/bin/env node
/**
 * studies-index.mjs: generate studies/INDEX.md from the snapshots.
 *
 * The index is a table of figures, and figures in this repository are never
 * typed. This script reads every studies/<folder>/snapshot.json, runs
 * audit() on it (which recomputes every metric from the raw readings), and
 * writes the table. A study that fails audit stops the script: the index
 * lists only what is publishable.
 *
 * Deterministic: the same snapshots give the same bytes. No clock.
 *
 * Usage:
 *   node scripts/studies-index.mjs           write studies/INDEX.md
 *   node scripts/studies-index.mjs --check   exit 1 if INDEX.md is not what would be written
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { audit } from '../src/audit.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const STUDIES = join(ROOT, 'studies');
const pct = (x) => (x == null ? 'n/a' : `${(x * 100).toFixed(0)}%`);

export function loadStudies() {
  if (!existsSync(STUDIES)) return [];
  return readdirSync(STUDIES, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== 'private' && existsSync(join(STUDIES, d.name, 'snapshot.json')))
    .map((d) => d.name)
    .sort()
    .map((folder) => {
      const snap = JSON.parse(readFileSync(join(STUDIES, folder, 'snapshot.json'), 'utf8'));
      const metaFile = join(STUDIES, folder, 'study.json');
      const meta = existsSync(metaFile) ? JSON.parse(readFileSync(metaFile, 'utf8')) : {};
      return { folder, snap, meta, audit: audit(snap) };
    });
}

export function buildIndex(studies) {
  const edge = (e) => {
    if (!e) return 'not reportable';
    return `${e.censored ? 'at least ' : ''}${e.dKm} km${e.fragile ? ' [fragile]' : ''}`;
  };
  const row = ({ folder, snap, meta, audit: a }) => {
    const s = a.metrics;
    const v = s.visibility;
    const p = s.pack;
    const depth = snap.method.observation?.listDepth;
    return (
      `| [${folder}](${folder}/README.md) | ${String(snap.startedAt).slice(0, 10)} | ${meta.place ?? 'n/a'} | ${snap.query} | ` +
      `${v.found}/${v.measured} (${pct(v.share)}) | ${p.inPack}/${p.measured} (${pct(p.share)}) | ${v.unreached} | ` +
      `${edge(s.reachEdge)} | ${edge(s.packEdge)} | ${s.goneBy ? `${s.goneBy.dKm} km` : 'not reportable'} | ` +
      `${s.archetype.reliable ? s.archetype.archetype : 'not reportable'} | ${depth ? `${depth.min}-${depth.max}` : 'not recorded'} | ` +
      `PASS, ${a.counts.warn} warning(s) | [report](${folder}/report.html) |`
    );
  };

  // Grouped by preset. The two share columns are shares of the sample points
  // that preset lays down, so a single table across presets is an invitation
  // to compare numbers that do not compare.
  const header =
    '| study | observed | place | query | visible / measured | in top 3 / measured | unreached | reach edge | top-3 edge | gone by | shape | list depth | audit | report |\n' +
    '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|';
  const groups = [...new Set(studies.map((x) => x.snap.method.preset))]
    .sort()
    .map((preset) => {
      const group = studies.filter((x) => x.snap.method.preset === preset);
      const m = group[0].snap.method;
      return `## Preset \`${preset}\`: ${m.rmin}-${m.rmax} km, ${m.budget} points, ${m.rings} rings

Shares in this table are shares of the sample points this preset lays down. They compare with each other and not with a study in another group.

${header}
${group.map(row).join('\n')}`;
    })
    .join('\n\n');

  const passes = [...new Set(studies.map((x) => x.snap.method.observation?.passes ?? 'unrecorded'))];
  const passNote =
    passes.length === 1 && passes[0] === 1
      ? 'Every study here is a single pass. Nothing in this repository measures how far a point moves between scans, because no study has been run twice; `falloff compare` is the command that would.'
      : `Passes per point across these studies: ${passes.join(', ')}.`;
  const providers = [...new Set(studies.map((x) => `\`${x.snap.provider.id}\` (${x.snap.provider.version})`))];

  return `# Studies

Generated by \`node scripts/studies-index.mjs\` from the snapshots in this folder. Do not edit by hand.

${studies.length} dated studies. Each is a real scan, observed on the date shown, not a live claim.
Every figure below is recomputed from the raw readings by \`falloff audit\`, and
every denominator is the number of points that were actually measured.

These scans were observed with an automated browser scan written by this
project's author. That scanner is not in this repository, and this repository
ships no scraper. The commands at the bottom re-render the recorded files;
re-observing these points needs your own provider.

Business names are withheld and ids are hashed with a salt that is not
published. Each centre is rounded to 0.01 degrees, about 1 km, and the sample
points are recomputed from the rounded centre, so the geometry still replays.
Withheld is not anonymous: the town, the query and the date are kept.

${groups}

Provider: ${providers.join('; ')}. Ranks are the order of the Google Maps results
feed as seen by a logged-out desktop browser at zoom 13. A scan through another
provider measures a different surface and is not comparable with these.
"List depth" is how many rows were captured per point: absent means absent from
a list of that depth.

${passNote}

A figure marked [fragile] would move if a re-scan changed one ring: a Wilson
95% interval on that ring or the next one out contains the threshold. "At
least X km" means the edge is on the outermost ring scanned, so the scan
cannot say how much further it reaches.

Recompute any row:

\`\`\`sh
falloff audit  studies/<study>/snapshot.json
falloff report studies/<study>/snapshot.json
\`\`\`

A pass means the file is internally consistent, not that the readings are
true. The README lists what the audit cannot know.
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const studies = loadStudies();
  const failed = studies.filter((s) => !s.audit.ok);
  if (failed.length) {
    console.error(`these studies do not pass audit: ${failed.map((s) => s.folder).join(', ')}`);
    process.exit(1);
  }
  const text = buildIndex(studies);
  const file = join(STUDIES, 'INDEX.md');
  if (process.argv.includes('--check')) {
    const same = existsSync(file) && readFileSync(file, 'utf8') === text;
    console.log(same ? `studies/INDEX.md is current (${studies.length} studies)` : 'studies/INDEX.md is stale. Run: node scripts/studies-index.mjs');
    process.exit(same ? 0 : 1);
  }
  writeFileSync(file, text);
  console.log(`studies/INDEX.md: ${studies.length} studies`);
}
